sudo: false
language: objective-c

before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
    # 32-bit tests
    - xctool -sdk iphonesimulator clean test -destination "name=iPhone 5" -find-target "JWTTests"
    # 64-bit tests
    - xctool -sdk iphonesimulator clean test -destination "name=iPhone 5s" -find-target "JWTTests"
    # os x
    - xctool -sdk macosx clean test -find-target "JWTTests_OSX"